### ISSUE TITLE
git LFS error downloading weights due to data quota

### ISSUE THREAD

**Issue by atong01** [aqlaboratory/genie2#1]
Hi,

Your weights are currently inaccessible due to the error below. Could you make them available through another method? I have hacked this before by attaching them to a release, although there are many ways. e.g. https://github.com/DreamFold/FoldFlow/releases/tag/0.1.0

```
Downloading results/base/checkpoints/epoch=30.ckpt (189 MB)
Error downloading object: results/base/checkpoints/epoch=30.ckpt (2f2ff84): Smudge error: Error downloading results/base/checkpoints/epoch=30.ckpt (2f2ff840f75f01f71e906e2a47649c35a1260cc060e04b4045c2fa4e2dd59823): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by yeqinglin** [comment]
We make a v1.0.0 release with the two checkpoints. Let's us know if you face any further issue.

**Comment by atong01** [comment]
Thank you for your prompt response. Works for me.
