### ISSUE TITLE
LFS Quota Exceeded

### ISSUE THREAD

**Issue by colbyford** [aqlaboratory/genie2#3]
It appears that this repository has hit its Git LFS quota and thus users cannot pull the checkpoint data, etc.

```
root@f39e43136e39:/app/genie2/results/base# git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/aqlaboratory/genie2.git/info/lfs'
```

**Comment by yeqinglin** [comment]
Thanks for pointing this out and please refer to [Issue 1](https://github.com/aqlaboratory/genie2/issues/1) for solution. We will update our README on this.
